import { GithubUser } from '@/interfaces';
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [users, setUsers] = useState<GithubUser[]>([]);

  useEffect(() => {
    const fetchUsers = async () => {
      const response = await fetch('api/v1/users');
      const data = await response.json();
      setUsers(data);
    }
    fetchUsers();
  }, [])

  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <table>
          <thead>
            <tr>
              <th>id</th>
              <th>name</th>
              <th>url</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user.id}>
                <a href={`/user/${user.login}`}>
                  <td>{user.id}</td>
                  <td>{user.login}</td>
                  <td><a>{user.url}</a></td>
                </a>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  )
}
