import { GithubUser } from "@/interfaces";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function User() {
  const router = useRouter();

  const [user, setUser] = useState<GithubUser>();
  const { username } = router.query;

  useEffect(() => {
    if (!username) return;

    const fetchUser = async () => {
      const user = await fetch(`/api/v1/user/${username}`);
      const data = await user.json();
      setUser(data);
    }
    fetchUser();
  }, [username])

  if (!user) return null;

  return (
    <>
      <Head>
        <title>User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <table>
          <thead>
            <tr>
              <th>id</th>
              <th>name</th>
              <th>url</th>
              <th>repos</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{user.id}</td>
              <td>{user.login}</td>
              <td>{user.url}</td>
              <td><a href={`/user/${user.login}/repos`}>Repos</a></td>
            </tr>
          </tbody>
        </table>
      </main>
    </>
  );
}